### ISSUE TITLE
[FEATURE]: PWA Ready

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#43]
## Summary

Make it work like a PWA!

![image](https://user-images.githubusercontent.com/9373787/66840549-2a794400-ef60-11e9-966a-26ce6c634118.png)

### Motivation

PWA is a new thing and devs just love new things, don't we? 😆

**Comment by vincentdoerig** [comment]
Hi, can I take this up?

And can I just write `serviceWorker.register()` in the [index.js](https://github.com/xgeekshq/js-intl-kitchen-sink/blob/master/src/index.js) file, since create-react-app already provides a [serviceWorker.js](https://github.com/xgeekshq/js-intl-kitchen-sink/blob/master/src/serviceWorker.js) file or do you want me to create a more simple serviceWorker from scratch?

**Comment by luisFilipePT** [comment]
@vincentdoerig go for it 🚀 
You can use the one that React provides but you will probably have to add images and touch the manifesto file.

When you open the PR please attach the screenshot of PWA from lighthouse 🙏

**Comment by luisFilipePT** [comment]
@vincentdoerig added you to the contributors, thanks again
