### ISSUE TITLE
[FEATURE]: Improvement on tooltips in DateTimeFormat page

### ISSUE THREAD

**Issue by luisFilipePT** [xgeekshq/js-intl-kitchen-sink#89]
## Summary

Current tooltips/popovers on DateTimeFormat page look great but there's a small room for improvements:

- Remove options from the help test on the tooltips
- Add an help icon close to the label so that the suer perceives there's more info available
![image](https://user-images.githubusercontent.com/9373787/67166696-a113a880-f389-11e9-8cf0-71ec2f2a299f.png)
-Set a max width for the tooltips ex: 40% of the screen width to facilitate reading and looks

![image](https://user-images.githubusercontent.com/9373787/67166681-732e6400-f389-11e9-9452-a2005c182083.png)

### Motivation

Create a solid and great looking solution for popovers/help text to use in the next pages
Continue improvement

**Comment by luisFilipePT** [comment]
assign to @fllprbt (please and a comment in the issue so that i might assign it to you officially 🙏)

**Comment by triartleet** [comment]
Yeah, please assign me.

Considering that all labels are going to be hoverable, I think that the question mark may look a little tiring/repetitive (because it is going to be put next to each one of them). On the other hand, there should be some sort of indication for the hover action. I have not thought yet of any better way.. As long as nothing comes up, I will stick to the icon implementation.

**Comment by triartleet** [comment]
Still on this.

**Comment by luisFilipePT** [comment]
ok @fllprbt np
